/*
 * FF1 Decompiled Functions - Map Exit & Entity Resolution
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding map exit destination resolution for screen reader
 *
 * Key investigation areas:
 *   - FieldMapProvisionInformation: How CurrentMapId is tracked/updated
 *   - MapManager.CurrentMapModel: Authoritative source for current map
 *   - PropertyGotoMap.MapId: How destination map ID is determined
 *   - GotoMapEventEntity.SetProperty: How exit properties are assigned
 *
 * Known issue: Map exits showing wrong destinations (e.g., exits inside
 * Cornelia showing 'Exit to Chaos Shrine' instead of 'Exit to World Map')
 */


/====================================================================/
/* FieldMapProvisionInformation
 ===================================================================/

/********************************************************************/
/* FieldMapProvisionInformation$$SetFreeSaveArea
 * RVA: 0x957F30
 * Address: 0x180957F30
 *******************************************************************/


void FUN_180957f30(longlong param_1,longlong param_2)

{
  code *pcVar1;
  char cVar2;
  
  if (param_2 == 0) {
    cVar2 = '\0';
  }
  else {
    cVar2 = *(char *)(param_2 + 0x2d);
  }
  if (param_1 != 0) {
    *(bool *)(param_1 + 0x1c) = cVar2 != '\0';
    return;
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* FieldMapProvisionInformation$$get_CurrentMapId
 * RVA: 0x268180
 * Address: 0x180268180
 *******************************************************************/


undefined4 FUN_180268180(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x10);
}



/********************************************************************/
/* FieldMapProvisionInformation$$get_FieldMapPos
 * RVA: 0x958010
 * Address: 0x180958010
 *******************************************************************/


undefined8 FieldMapProvisionInformation_get_FieldMapPos(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x14);
}



/********************************************************************/
/* FieldMapProvisionInformation$$get_Instance
 * RVA: 0x958030
 * Address: 0x180958030
 *******************************************************************/


undefined8 FUN_180958030(void)

{
  longlong *plVar1;
  longlong lVar2;
  undefined8 uVar3;
  undefined4 local_res10;
  undefined4 uStackX_14;
  
  if (DAT_181f53c85 == '\0') {
    thunk_FUN_1801fec80(DAT_18174cbf8);
    DAT_181f53c85 = '\x01';
  }
  if (((*(byte *)(DAT_18225d768 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d768 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  if (**(longlong **)(DAT_18225d768 + 0xb8) == 0) {
    lVar2 = thunk_FUN_1802038d0();
    if (DAT_181f53c8a == '\0') {
      thunk_FUN_1801fec80(DAT_18174cbe8);
      DAT_181f53c8a = '\x01';
    }
    if (((*(byte *)(DAT_18220f448 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f448 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar3 = FUN_1814ce1c0(0);
    local_res10 = (undefined4)uVar3;
    uStackX_14 = (undefined4)((ulonglong)uVar3 >> 0x20);
    *(undefined4 *)(lVar2 + 0x14) = local_res10;
    *(undefined4 *)(lVar2 + 0x18) = uStackX_14;
    uVar3 = thunk_FUN_1802038d0(DAT_182243c08);
    FUN_180db95f0(uVar3,DAT_182227a60);
    *(undefined8 *)(lVar2 + 0x20) = uVar3;
    thunk_FUN_180234b30((undefined8 *)(lVar2 + 0x20),uVar3);
    FUN_1802698f0(lVar2,0);
    if (((*(byte *)(DAT_18225d768 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d768 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    plVar1 = *(longlong **)(DAT_18225d768 + 0xb8);
    *plVar1 = lVar2;
    thunk_FUN_180234b30(plVar1,lVar2);
  }
  if (((*(byte *)(DAT_18225d768 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d768 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
    return **(undefined8 **)(DAT_18225d768 + 0xb8);
  }
  return **(undefined8 **)(DAT_18225d768 + 0xb8);
}



/********************************************************************/
/* FieldMapProvisionInformation$$set_CurrentMapId
 * RVA: 0x269340
 * Address: 0x180269340
 *******************************************************************/


void FUN_180269340(longlong param_1,undefined4 param_2)

{
  *(undefined4 *)(param_1 + 0x10) = param_2;
  return;
}



/====================================================================/
/* GotoMapEventEntity
 ===================================================================/

/********************************************************************/
/* GotoMapEventEntity$$CanEnter
 * RVA: 0xF6A350
 * Address: 0x180F6A350
 *******************************************************************/


/* WARNING: Removing unreachable block (ram,0x000180f6a428) */

bool FUN_180f6a350(undefined8 param_1,longlong *param_2,undefined8 param_3)

{
  longlong lVar1;
  char cVar2;
  
  if (DAT_181f57603 == '\0') {
    thunk_FUN_1801fec80(DAT_181755ab4);
    DAT_181f57603 = '\x01';
  }
  cVar2 = FUN_1802680c0(param_1,param_2,param_3,0);
  if (cVar2 == '\0') {
    return false;
  }
  if (param_2 == (longlong *)0x0) {
    param_2 = (longlong *)0x0;
  }
  else {
    lVar1 = *param_2;
    if ((*(byte *)(DAT_1822503c8 + 0x128) <= *(byte *)(lVar1 + 0x128)) &&
       (*(longlong *)
         (*(longlong *)(lVar1 + 200) + -8 + (ulonglong)*(byte *)(DAT_1822503c8 + 0x128) * 8) ==
        DAT_1822503c8)) {
      return true;
    }
    if ((*(byte *)(lVar1 + 0x128) < *(byte *)(DAT_18225d710 + 0x128)) ||
       (*(longlong *)
         (*(longlong *)(lVar1 + 200) + -8 + (ulonglong)*(byte *)(DAT_18225d710 + 0x128) * 8) !=
        DAT_18225d710)) {
      param_2 = (longlong *)0x0;
    }
  }
  return param_2 != (longlong *)0x0;
}



/********************************************************************/
/* GotoMapEventEntity$$SetProperty
 * RVA: 0xF6A470
 * Address: 0x180F6A470
 *******************************************************************/


void GotoMapEventEntity_SetProperty(undefined8 param_1,undefined8 param_2)

{
  FUN_1807e8150(param_1,param_2,0);
  return;
}



/====================================================================/
/* MapLoadProcessor
 ===================================================================/

/********************************************************************/
/* MapLoadProcessor$$GetMapManager
 * RVA: 0x2BF5C0
 * Address: 0x1802BF5C0
 *******************************************************************/


longlong FUN_1802bf5c0(void)

{
  longlong *plVar1;
  code *pcVar2;
  longlong lVar3;
  
  if (DAT_181f4dfce == '\0') {
    thunk_FUN_1801fec80(DAT_181749604);
    DAT_181f4dfce = '\x01';
  }
  if (((*(byte *)(DAT_18225de60 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225de60 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_1802bfe80(0);
  if (lVar3 != 0) {
    plVar1 = (longlong *)(lVar3 + 0x20);
    lVar3 = *(longlong *)(lVar3 + 0x20);
    if (lVar3 == 0) {
      lVar3 = thunk_FUN_1802038d0(DAT_182242510);
      FUN_1802698f0(lVar3,0);
      FUN_1802c89e0(lVar3,0);
      *plVar1 = lVar3;
      thunk_FUN_180234b30(plVar1,lVar3);
      lVar3 = *plVar1;
    }
    return lVar3;
  }
  FUN_180237800();
  pcVar2 = (code *)swi(3);
  lVar3 = (*pcVar2)();
  return lVar3;
}



/********************************************************************/
/* MapLoadProcessor$$get_Instance
 * RVA: 0x2BFE80
 * Address: 0x1802BFE80
 *******************************************************************/


undefined8 FUN_1802bfe80(void)

{
  undefined8 *puVar1;
  undefined8 uVar2;
  
  if (DAT_181f4dfcc == '\0') {
    thunk_FUN_1801fec80(DAT_181749630);
    DAT_181f4dfcc = '\x01';
  }
  if (((*(byte *)(DAT_18225de60 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225de60 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  if (**(longlong **)(DAT_18225de60 + 0xb8) == 0) {
    uVar2 = thunk_FUN_1802038d0();
    FUN_1802698f0(uVar2,0);
    if (((*(byte *)(DAT_18225de60 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225de60 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    puVar1 = *(undefined8 **)(DAT_18225de60 + 0xb8);
    *puVar1 = uVar2;
    thunk_FUN_180234b30(puVar1,uVar2);
  }
  if (((*(byte *)(DAT_18225de60 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225de60 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
    return **(undefined8 **)(DAT_18225de60 + 0xb8);
  }
  return **(undefined8 **)(DAT_18225de60 + 0xb8);
}



/====================================================================/
/* MapManager
 ===================================================================/

/********************************************************************/
/* MapManager$$SearchEntity
 * RVA: 0x2CB600
 * Address: 0x1802CB600
 *******************************************************************/


void FUN_1802cb600(undefined4 param_1,longlong param_2)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  
  if (DAT_181f4e01d == '\0') {
    thunk_FUN_1801fec80(DAT_181749d8c);
    DAT_181f4e01d = '\x01';
  }
  if ((param_2 != 0) && (*(longlong *)(param_2 + 0x18) != 0)) {
    lVar2 = thunk_FUN_1802038d0(DAT_182241c68);
    FUN_180268140(lVar2,0);
    if (lVar2 == 0) {
      FUN_180237800();
      pcVar1 = (code *)swi(3);
      (*pcVar1)();
      return;
    }
    *(undefined4 *)(lVar2 + 0x10) = param_1;
    uVar3 = thunk_FUN_1802038d0(DAT_1822444d8);
    FUN_1802e1730(uVar3,lVar2,DAT_182251af0,DAT_182215a00);
    uVar3 = FUN_180438200(param_2,uVar3,DAT_18221f2d0);
    uVar3 = FUN_180de72a0(uVar3,DAT_182214120);
    FUN_180998e80(uVar3,DAT_182240de8);
  }
  return;
}



/********************************************************************/
/* MapManager$$SetCurrentMap
 * RVA: 0x272010
 * Address: 0x180272010
 *******************************************************************/


void FUN_180272010(longlong param_1,undefined4 param_2)

{
  longlong lVar1;
  code *pcVar2;
  longlong lVar3;
  char cVar4;
  undefined8 uVar5;
  
  if (DAT_181f4da1e == '\0') {
    thunk_FUN_1801fec80(DAT_1817472c0);
    DAT_181f4da1e = '\x01';
  }
  *(undefined4 *)(param_1 + 0x68) = param_2;
  if (*(longlong *)(param_1 + 0x70) != 0) {
    cVar4 = FUN_1811039f0(*(longlong *)(param_1 + 0x70),param_2,DAT_1822389a8);
    if (cVar4 == '\0') {
      lVar1 = *(longlong *)(param_1 + 0x70);
      lVar3 = thunk_FUN_1802038d0(DAT_182245208);
      if (DAT_181f4da24 == '\0') {
        thunk_FUN_1801fec80(DAT_181756bdc);
        DAT_181f4da24 = '\x01';
      }
      FUN_1802698f0(lVar3,0);
      uVar5 = thunk_FUN_1802038d0(DAT_182245278);
      FUN_181112b80(uVar5,DAT_182232468);
      *(undefined8 *)(lVar3 + 0x10) = uVar5;
      thunk_FUN_180234b30((undefined8 *)(lVar3 + 0x10),uVar5);
      if (lVar1 == 0) goto LAB_1802720f9;
      FUN_1812b14a0(lVar1,param_2,lVar3,DAT_182239a78);
    }
    return;
  }
LAB_1802720f9:
  FUN_180237800();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* MapManager$$get_CashGotoMapProperty
 * RVA: 0x2CE540
 * Address: 0x1802CE540
 *******************************************************************/


undefined8 MapManager_get_CashGotoMapProperty(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x198);
}



/********************************************************************/
/* MapManager$$get_CurrentMapModel
 * RVA: 0x2CE550
 * Address: 0x1802CE550
 *******************************************************************/


undefined8 FUN_1802ce550(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x188);
}



/====================================================================/
/* MapModel
 ===================================================================/

/********************************************************************/
/* MapModel$$GetAreaId
 * RVA: 0x300310
 * Address: 0x180300310
 *******************************************************************/


undefined8 FUN_180300310(longlong param_1)

{
  undefined8 uVar1;
  
  if (*(longlong *)(param_1 + 0x10) != 0) {
    uVar1 = FUN_180c7a990(*(longlong *)(param_1 + 0x10),0);
    return uVar1;
  }
  return 0;
}



/********************************************************************/
/* MapModel$$GetAreaNameId
 * RVA: 0x300330
 * Address: 0x180300330
 *******************************************************************/


longlong FUN_180300330(longlong param_1)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  
  if (DAT_181f4e223 == '\0') {
    thunk_FUN_1801fec80(DAT_181749f40);
    DAT_181f4e223 = '\x01';
  }
  if (*(longlong *)(param_1 + 0x18) != 0) {
    lVar3 = FUN_180c7a710(*(longlong *)(param_1 + 0x18),0);
    if (lVar3 != 0) goto LAB_18030037d;
  }
  lVar3 = **(longlong **)(DAT_18221c5e8 + 0xb8);
LAB_18030037d:
  if (DAT_182215d58 != 0) {
    cVar2 = FUN_180ff0540(DAT_182215d58,lVar3,0);
    if (cVar2 != '\0') {
      lVar3 = **(longlong **)(DAT_18221c5e8 + 0xb8);
    }
    return lVar3;
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  lVar3 = (*pcVar1)();
  return lVar3;
}



/********************************************************************/
/* MapModel$$GetId
 * RVA: 0x2B9790
 * Address: 0x1802B9790
 *******************************************************************/


undefined4 FUN_1802b9790(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x20);
}



/********************************************************************/
/* MapModel$$GetMapName
 * RVA: 0x300960
 * Address: 0x180300960
 *******************************************************************/


longlong FUN_180300960(longlong param_1)

{
  longlong lVar1;
  
  lVar1 = *(longlong *)(param_1 + 0x40);
  if (lVar1 != 0) {
    return *(longlong *)(lVar1 + 0x18);
  }
  return lVar1;
}



/********************************************************************/
/* MapModel$$GetTitleId
 * RVA: 0x300AD0
 * Address: 0x180300AD0
 *******************************************************************/


longlong FUN_180300ad0(longlong param_1)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  
  if (DAT_181f4e222 == '\0') {
    thunk_FUN_1801fec80(DAT_18174a03c);
    DAT_181f4e222 = '\x01';
  }
  if (*(longlong *)(param_1 + 0x10) != 0) {
    lVar3 = FUN_180c80870(*(longlong *)(param_1 + 0x10),0);
    if (lVar3 != 0) goto LAB_180300b1d;
  }
  lVar3 = **(longlong **)(DAT_18221c5e8 + 0xb8);
LAB_180300b1d:
  if (DAT_182215d58 != 0) {
    cVar2 = FUN_180ff0540(DAT_182215d58,lVar3,0);
    if (cVar2 != '\0') {
      lVar3 = **(longlong **)(DAT_18221c5e8 + 0xb8);
    }
    return lVar3;
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  lVar3 = (*pcVar1)();
  return lVar3;
}



/********************************************************************/
/* MapModel$$ctor
 * RVA: 0x301420
 * Address: 0x180301420
 *******************************************************************/


void FUN_180301420(longlong param_1,undefined4 param_2,undefined8 param_3)

{
  code *pcVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  int iVar4;
  longlong lVar5;
  undefined8 uVar6;
  
  if (DAT_181f4e221 == '\0') {
    thunk_FUN_1801fec80(DAT_18174a0e8);
    DAT_181f4e221 = '\x01';
  }
  FUN_1802698f0(param_1,0);
  if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar5 = FUN_180ea8da0(DAT_182245a60);
  if (lVar5 != 0) {
    uVar6 = FUN_1808fb990(lVar5,param_2,DAT_182256778);
    *(undefined8 *)(param_1 + 0x10) = uVar6;
    thunk_FUN_180234b30(param_1 + 0x10,uVar6);
    uVar3 = 0;
    uVar2 = uVar3;
    if (*(longlong *)(param_1 + 0x10) != 0) {
      uVar2 = FUN_180c7a990(*(longlong *)(param_1 + 0x10),0);
    }
    uVar6 = FUN_1808fb990(lVar5,uVar2,DAT_182256c80);
    *(undefined8 *)(param_1 + 0x18) = uVar6;
    thunk_FUN_180234b30(param_1 + 0x18,uVar6);
    *(undefined8 *)(param_1 + 0x40) = param_3;
    *(undefined4 *)(param_1 + 0x20) = param_2;
    thunk_FUN_180234b30((undefined8 *)(param_1 + 0x40),param_3);
    if (*(longlong *)(param_1 + 0x10) != 0) {
      uVar3 = FUN_180c7a9d0(*(longlong *)(param_1 + 0x10),0);
    }
    *(undefined4 *)(param_1 + 0x24) = uVar3;
    if (*(longlong *)(param_1 + 0x18) == 0) {
      iVar4 = -1;
    }
    else {
      iVar4 = FUN_180c794d0(*(longlong *)(param_1 + 0x18),0);
    }
    *(int *)(param_1 + 0x28) = iVar4;
    *(bool *)(param_1 + 0x2c) = iVar4 == 0;
    if (*(longlong *)(param_1 + 0x10) != 0) {
      iVar4 = FUN_180c7a590(*(longlong *)(param_1 + 0x10),0);
      *(bool *)(param_1 + 0x2d) = iVar4 == 1;
      uVar6 = thunk_FUN_1802038d0(DAT_182241a00);
      FUN_181112b80(uVar6,DAT_1822336c0);
      *(undefined8 *)(param_1 + 0x48) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x48),uVar6);
      uVar6 = thunk_FUN_1802038d0(DAT_1822419b8);
      FUN_181112b80(uVar6,DAT_182233618);
      *(undefined8 *)(param_1 + 0x50) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x50),uVar6);
      uVar6 = thunk_FUN_1802038d0(DAT_1822419b0);
      FUN_181112b80(uVar6,DAT_182233750);
      *(undefined8 *)(param_1 + 0x58) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x58),uVar6);
      uVar6 = thunk_FUN_1802038d0(DAT_18221c4e0);
      FUN_180db95f0(uVar6,DAT_18221f440);
      *(undefined8 *)(param_1 + 0x70) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x70),uVar6);
      uVar6 = thunk_FUN_1802038d0(DAT_182241958);
      FUN_181112b80(uVar6,DAT_1822334f8);
      *(undefined8 *)(param_1 + 0x60) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x60),uVar6);
      uVar6 = thunk_FUN_1802038d0(DAT_182241ec8);
      FUN_180db95f0(uVar6,DAT_182225a10);
      *(undefined8 *)(param_1 + 0x68) = uVar6;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0x68),uVar6);
      return;
    }
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* MapModel$$get_IsAreaTypeWorld
 * RVA: 0x3016B0
 * Address: 0x1803016B0
 *******************************************************************/


undefined MapModel_get_IsAreaTypeWorld(longlong param_1)

{
  return *(undefined *)(param_1 + 0x2c);
}



/====================================================================/
/* PropertyEntity
 ===================================================================/

/********************************************************************/
/* PropertyEntity$$ConvertPropertyToData
 * RVA: 0x52FF30
 * Address: 0x18052FF30
 *******************************************************************/


void FUN_18052ff30(longlong param_1,longlong param_2)

{
  code *pcVar1;
  undefined4 uVar2;
  char cVar3;
  undefined8 local_res10 [3];
  
  if (DAT_181f4f721 == '\0') {
    thunk_FUN_1801fec80(DAT_1817c46c4);
    DAT_181f4f721 = '\x01';
  }
  FUN_1805306c0(param_1,param_2,0);
  if (param_2 != 0) {
    *(undefined *)(param_1 + 0x98) = *(undefined *)(param_2 + 0x68);
    *(undefined *)(param_1 + 0xb0) = *(undefined *)(param_2 + 0x125);
    cVar3 = (char)*(undefined2 *)(param_2 + 0x126);
    if ((char)((ushort)*(undefined2 *)(param_2 + 0x126) >> 8) == '\0') {
      cVar3 = '\x01';
    }
    *(bool *)(param_1 + 0xb1) = cVar3 != '\0';
    *(undefined *)(param_1 + 0xb8) = *(undefined *)(param_2 + 0x141);
    *(undefined4 *)(param_1 + 0xbc) = *(undefined4 *)(param_2 + 0x144);
    *(undefined *)(param_1 + 0xc0) = *(undefined *)(param_2 + 0x4d);
    *(undefined *)(param_1 + 0xc1) = *(undefined *)(param_2 + 0x181);
    if (*(char *)(param_2 + 0x181) != '\0') {
      *(undefined *)(param_1 + 0xb1) = 0;
      *(undefined *)(param_1 + 0x2c) = 0;
    }
    if ((*(char *)(param_2 + 0x125) == '\0') || (uVar2 = 2, -1 < *(int *)(param_2 + 0x128))) {
      uVar2 = *(undefined4 *)(param_2 + 0x128);
    }
    *(undefined4 *)(param_1 + 0xb4) = uVar2;
    if (*(char *)(param_2 + 0x140) != '\0') {
      *(undefined4 *)(param_1 + 0xc4) = 8;
    }
    local_res10[0] = **(undefined8 **)(DAT_18221c5e8 + 0xb8);
    FUN_180cb1580(param_2,local_res10,0);
    *(undefined8 *)(param_1 + 0xa0) = local_res10[0];
    thunk_FUN_180234b30();
    *(undefined8 *)(param_1 + 0xa8) = DAT_18225a3b0;
    thunk_FUN_180234b30();
    return;
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/====================================================================/
/* PropertyGotoMap
 ===================================================================/

/********************************************************************/
/* PropertyGotoMap$$ConvertPropertyToData
 * RVA: 0x530910
 * Address: 0x180530910
 *******************************************************************/


void FUN_180530910(longlong param_1,longlong param_2)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  
  if (DAT_181f4f725 == '\0') {
    thunk_FUN_1801fec80(DAT_1817c4724);
    DAT_181f4f725 = '\x01';
  }
  FUN_1805306c0(param_1,param_2,0);
  if (param_2 != 0) {
    *(undefined4 *)(param_1 + 0x98) = *(undefined4 *)(param_2 + 0x3c);
    if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar2 = FUN_180ea8da0(DAT_182245a60);
    if (lVar2 != 0) {
      lVar2 = FUN_1808fb990(lVar2,*(undefined4 *)(param_1 + 0x98),DAT_182256778);
      if (lVar2 == 0) {
        uVar3 = 0;
        *(undefined8 *)(param_1 + 0xa0) = 0;
        thunk_FUN_180234b30((undefined8 *)(param_1 + 0xa0),0);
      }
      else {
        uVar3 = FUN_180c7db90(lVar2);
        *(undefined8 *)(param_1 + 0xa0) = uVar3;
        thunk_FUN_180234b30((undefined8 *)(param_1 + 0xa0),uVar3);
        uVar3 = FUN_180c7a710(lVar2,0);
      }
      *(undefined8 *)(param_1 + 0xa8) = uVar3;
      thunk_FUN_180234b30((undefined8 *)(param_1 + 0xa8),uVar3);
      *(undefined4 *)(param_1 + 0xb0) = *(undefined4 *)(param_2 + 0x40);
      return;
    }
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* PropertyGotoMap$$ctor
 * RVA: 0x5307B0
 * Address: 0x1805307B0
 *******************************************************************/


void FUN_1805307b0(longlong *param_1,undefined8 param_2)

{
  *(undefined4 *)(param_1 + 0x12) = 0xffffffff;
  FUN_1802698f0(param_1,0);
                    /* WARNING: Could not recover jumptable at 0x0001805307eb. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(*param_1 + 0x170))(param_1,param_2,*(undefined8 *)(*param_1 + 0x178));
  return;
}



/********************************************************************/
/* PropertyGotoMap$$get_AssetName
 * RVA: 0x2BA5A0
 * Address: 0x1802BA5A0
 *******************************************************************/


undefined8 PropertyGotoMap_get_AssetName(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0xa8);
}



/********************************************************************/
/* PropertyGotoMap$$get_MapId
 * RVA: 0x311160
 * Address: 0x180311160
 *******************************************************************/


undefined4 FUN_180311160(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x98);
}



/********************************************************************/
/* PropertyGotoMap$$set_MapId
 * RVA: 0x3111A0
 * Address: 0x1803111A0
 *******************************************************************/


void PropertyGotoMap_set_MapId(longlong param_1,undefined4 param_2)

{
  *(undefined4 *)(param_1 + 0x98) = param_2;
  return;
}

