/*
 * FF1 Decompiled Functions - Magic/Ability System
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding FF1's spell system for screen reader accessibility
 *
 * FF1 Magic System:
 *   - Classic spell charge system (spell uses per rest)
 *   - 8 spell levels, each with limited charges
 *   - 3 spell slots per level per character
 *   - Spells purchased from shops and assigned to slots
 *
 * Key classes:
 *   - OwnedAbility: Player's spell instance with name/description
 *   - Ability: Master data for spell properties (damage, MP cost, etc.)
 *   - OwnedAbilitySlotData: Spell slot management per level
 *   - OwnedCharacterClient: Character spell assignment operations
 */


/====================================================================/
/* Ability
 ===================================================================/

/********************************************************************/
/* Ability$$ctor_masterLine
 * RVA: 0xC7A120
 * Address: 0x180C7A120
 *******************************************************************/


void FUN_180c7a120(undefined8 param_1,undefined8 param_2)

{
  if (DAT_181f55c72 == '\0') {
    thunk_FUN_1801fec80(DAT_1817c7af4);
    DAT_181f55c72 = '\x01';
  }
  FUN_180268140(param_1,0);
  if (((*(byte *)(DAT_182253b70 + 0x12f) & 2) != 0) && (*(int *)(DAT_182253b70 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_182253b70);
  }
  FUN_1805e9010(param_1,*(longlong *)(DAT_182253b70 + 0xb8) + 8,DAT_18223fa40);
  FUN_181025fe0(param_1,*(longlong *)(DAT_182253b70 + 0xb8) + 8,param_2,0);
  return;
}



/********************************************************************/
/* Ability$$get_AbilityGroupId
 * RVA: 0xC799E0
 * Address: 0x180C799E0
 *******************************************************************/


ulonglong FUN_180c799e0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (3 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x2c);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_AbilityLv
 * RVA: 0xC79510
 * Address: 0x180C79510
 *******************************************************************/


ulonglong FUN_180c79510(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (2 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x28);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_AttributeId
 * RVA: 0xC7A310
 * Address: 0x180C7A310
 *******************************************************************/


ulonglong FUN_180c7a310(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (5 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x34);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_Id
 * RVA: 0xC792A0
 * Address: 0x180C792A0
 *******************************************************************/


ulonglong FUN_180c792a0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (*(int *)(lVar1 + 0x18) != 0) {
    return (ulonglong)*(uint *)(lVar1 + 0x20);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_StandardValue
 * RVA: 0xC7A890
 * Address: 0x180C7A890
 *******************************************************************/


ulonglong FUN_180c7a890(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (9 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x44);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_SystemId
 * RVA: 0xC7A8D0
 * Address: 0x180C7A8D0
 *******************************************************************/


ulonglong FUN_180c7a8d0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (7 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x3c);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_TypeId
 * RVA: 0xC799A0
 * Address: 0x180C799A0
 *******************************************************************/


ulonglong FUN_180c799a0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (4 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x30);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_UseJobGroupId
 * RVA: 0xC7A910
 * Address: 0x180C7A910
 *******************************************************************/


ulonglong FUN_180c7a910(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (0x10 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x60);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_UseValue
 * RVA: 0xC7A950
 * Address: 0x180C7A950
 *******************************************************************/


ulonglong FUN_180c7a950(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (8 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x40);
  }
  uVar3 = thunk_FUN_1801f50f0();
  FUN_1802377d0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/====================================================================/
/* OwnedAbility
 ===================================================================/

/********************************************************************/
/* OwnedAbility$$ctor
 * RVA: 0x3B7FA0
 * Address: 0x1803B7FA0
 *******************************************************************/


void FUN_1803b7fa0(longlong param_1,longlong param_2,longlong param_3,undefined4 param_4)

{
  longlong lVar1;
  code *pcVar2;
  undefined4 uVar3;
  undefined8 uVar4;
  
  if (DAT_181f4e9a8 == '\0') {
    thunk_FUN_1801fec80(DAT_18175799c);
    DAT_181f4e9a8 = '\x01';
  }
  uVar4 = thunk_FUN_1802038d0(DAT_182252280);
  FUN_1802698f0(uVar4,0);
  *(undefined8 *)(param_1 + 0x20) = uVar4;
  thunk_FUN_180234b30(param_1 + 0x20,uVar4);
  FUN_1802698f0(param_1,0);
  *(longlong *)(param_1 + 0x10) = param_2;
  thunk_FUN_180234b30(param_1 + 0x10,param_2);
  if (*(longlong *)(param_1 + 0x10) != 0) {
    lVar1 = *(longlong *)(param_1 + 0x20);
    if (param_2 == 0) goto LAB_1803b809c;
    uVar3 = FUN_180c792a0(param_2,0);
    if (lVar1 == 0) goto LAB_1803b809c;
    *(undefined4 *)(lVar1 + 0x10) = uVar3;
  }
  *(longlong *)(param_1 + 0x18) = param_3;
  thunk_FUN_180234b30(param_1 + 0x18,param_3);
  if (*(longlong *)(param_1 + 0x18) != 0) {
    lVar1 = *(longlong *)(param_1 + 0x20);
    if (param_3 != 0) {
      uVar3 = FUN_180c792a0(param_3,0);
      if (lVar1 != 0) {
        *(undefined4 *)(lVar1 + 0x14) = uVar3;
        goto LAB_1803b8076;
      }
    }
LAB_1803b809c:
    FUN_180237800();
    pcVar2 = (code *)swi(3);
    (*pcVar2)();
    return;
  }
LAB_1803b8076:
  if (*(longlong *)(param_1 + 0x20) != 0) {
    *(undefined4 *)(*(longlong *)(param_1 + 0x20) + 0x18) = param_4;
  }
  return;
}



/********************************************************************/
/* OwnedAbility$$get_Ability
 * RVA: 0x272320
 * Address: 0x180272320
 *******************************************************************/


undefined8 FUN_180272320(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x10);
}



/********************************************************************/
/* OwnedAbility$$get_Content
 * RVA: 0x268150
 * Address: 0x180268150
 *******************************************************************/


undefined8 FUN_180268150(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x18);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdDescription
 * RVA: 0x3B80B0
 * Address: 0x1803B80B0
 *******************************************************************/


longlong FUN_1803b80b0(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181f4e9a7 == '\0') {
    thunk_FUN_1801fec80(DAT_1817579b4);
    DAT_181f4e9a7 = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180c80870(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_18221c5e8 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdName
 * RVA: 0x3B8100
 * Address: 0x1803B8100
 *******************************************************************/


longlong FUN_1803b8100(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181f4e9a6 == '\0') {
    thunk_FUN_1801fec80(DAT_1817579c4);
    DAT_181f4e9a6 = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180c7a710(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_18221c5e8 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_SkillLevel
 * RVA: 0x3B8150
 * Address: 0x1803B8150
 *******************************************************************/


ulonglong FUN_1803b8150(longlong param_1)

{
  ulonglong uVar1;
  
  uVar1 = *(ulonglong *)(param_1 + 0x20);
  if (uVar1 != 0) {
    return (ulonglong)*(uint *)(uVar1 + 0x18);
  }
  return uVar1;
}



/********************************************************************/
/* OwnedAbility$$set_SkillLevel
 * RVA: 0x3B8220
 * Address: 0x1803B8220
 *******************************************************************/


void FUN_1803b8220(longlong param_1,undefined4 param_2)

{
  if (*(longlong *)(param_1 + 0x20) != 0) {
    *(undefined4 *)(*(longlong *)(param_1 + 0x20) + 0x18) = param_2;
  }
  return;
}



/====================================================================/
/* OwnedAbilitySlotData
 ===================================================================/

/********************************************************************/
/* OwnedAbilitySlotData$$GetAbility
 * RVA: 0x3B7420
 * Address: 0x1803B7420
 *******************************************************************/


undefined8 FUN_1803b7420(longlong param_1,undefined4 param_2)

{
  code *pcVar1;
  char cVar2;
  undefined8 uVar3;
  
  if (DAT_181f4e9ad == '\0') {
    thunk_FUN_1801fec80(DAT_181757904);
    DAT_181f4e9ad = '\x01';
  }
  if (*(longlong *)(param_1 + 0x10) != 0) {
    cVar2 = FUN_1811039f0(*(longlong *)(param_1 + 0x10),param_2,DAT_182238c88);
    if (cVar2 == '\0') {
      return 0;
    }
    if (*(longlong *)(param_1 + 0x10) != 0) {
      uVar3 = FUN_1813fb000(*(longlong *)(param_1 + 0x10),param_2,DAT_1822084a8);
      return uVar3;
    }
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  uVar3 = (*pcVar1)();
  return uVar3;
}



/********************************************************************/
/* OwnedAbilitySlotData$$IsAllEmpty
 * RVA: 0x3B74A0
 * Address: 0x1803B74A0
 *******************************************************************/


void FUN_1803b74a0(longlong param_1)

{
  undefined8 uVar1;
  undefined8 uVar2;
  longlong lVar3;
  longlong *plVar4;
  
  if (DAT_181f4e9aa == '\0') {
    thunk_FUN_1801fec80(DAT_181757918);
    DAT_181f4e9aa = '\x01';
  }
  uVar1 = *(undefined8 *)(param_1 + 0x10);
  if (((*(byte *)(DAT_182252248 + 0x12f) & 2) != 0) && (*(int *)(DAT_182252248 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = *(longlong *)(*(longlong *)(DAT_182252248 + 0xb8) + 8);
  if (lVar3 == 0) {
    if (((*(byte *)(DAT_182252248 + 0x12f) & 2) != 0) && (*(int *)(DAT_182252248 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar2 = **(undefined8 **)(DAT_182252248 + 0xb8);
    lVar3 = thunk_FUN_1802038d0(DAT_182252220);
    FUN_1802e1730(lVar3,uVar2,DAT_182258b60,DAT_182212d40);
    plVar4 = (longlong *)(*(longlong *)(DAT_182252248 + 0xb8) + 8);
    *plVar4 = lVar3;
    thunk_FUN_180234b30(plVar4,lVar3);
  }
  FUN_180b60590(uVar1,lVar3,DAT_18222e210);
  return;
}



/********************************************************************/
/* OwnedAbilitySlotData$$SetAbility
 * RVA: 0x3B75A0
 * Address: 0x1803B75A0
 *******************************************************************/


void FUN_1803b75a0(longlong param_1,undefined4 param_2,undefined8 param_3)

{
  code *pcVar1;
  char cVar2;
  
  if (DAT_181f4e9ae == '\0') {
    thunk_FUN_1801fec80(DAT_181757930);
    DAT_181f4e9ae = '\x01';
  }
  if (*(longlong *)(param_1 + 0x10) != 0) {
    cVar2 = FUN_1811039f0(*(longlong *)(param_1 + 0x10),param_2,DAT_182238c88);
    if (cVar2 != '\0') {
      if (*(longlong *)(param_1 + 0x10) == 0) goto LAB_1803b7617;
      FUN_1812b14a0(*(longlong *)(param_1 + 0x10),param_2,param_3,DAT_18223a198);
    }
    return;
  }
LAB_1803b7617:
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* OwnedAbilitySlotData$$get_Level
 * RVA: 0x3B7D10
 * Address: 0x1803B7D10
 *******************************************************************/


ulonglong FUN_1803b7d10(longlong param_1)

{
  code *pcVar1;
  ulonglong uVar2;
  
  if (*(longlong *)(param_1 + 0x18) != 0) {
    return (ulonglong)*(uint *)(*(longlong *)(param_1 + 0x18) + 0x10);
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  uVar2 = (*pcVar1)();
  return uVar2;
}



/********************************************************************/
/* OwnedAbilitySlotData$$set_Level
 * RVA: 0x3B7D30
 * Address: 0x1803B7D30
 *******************************************************************/


void FUN_1803b7d30(longlong param_1,undefined4 param_2)

{
  code *pcVar1;
  
  if (*(longlong *)(param_1 + 0x18) != 0) {
    *(undefined4 *)(*(longlong *)(param_1 + 0x18) + 0x10) = param_2;
    return;
  }
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/====================================================================/
/* OwnedCharacterClient
 ===================================================================/

/********************************************************************/
/* OwnedCharacterClient$$AddAbility
 * RVA: 0x2A4050
 * Address: 0x1802A4050
 *******************************************************************/


longlong FUN_1802a4050(undefined8 param_1,undefined4 param_2,undefined4 param_3)

{
  code *pcVar1;
  char cVar2;
  undefined4 uVar3;
  longlong lVar4;
  longlong lVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  longlong lVar9;
  longlong *plVar10;
  undefined4 local_res10 [2];
  
  if (DAT_181f4df0f == '\0') {
    thunk_FUN_1801fec80(DAT_1817579e0);
    DAT_181f4df0f = '\x01';
  }
  lVar4 = thunk_FUN_1802038d0(DAT_18224a068);
  FUN_180268140(lVar4,0);
  if (lVar4 != 0) {
    *(undefined4 *)(lVar4 + 0x10) = param_2;
    *(undefined4 *)(lVar4 + 0x14) = param_3;
    if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar5 = FUN_180661ed0(0);
    if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar6 = FUN_180ea8da0(DAT_182245a60);
    if (lVar5 != 0) {
      uVar7 = FUN_1800dc890(0,DAT_182258c70,lVar5);
      uVar8 = thunk_FUN_1802038d0(DAT_18225e7f8);
      FUN_1802e1730(uVar8,lVar4,DAT_182254158,DAT_182215d50);
      uVar7 = FUN_180438200(uVar7,uVar8,DAT_18221f3b0);
      lVar5 = FUN_1808092c0(uVar7,DAT_18221bad0);
      if (lVar5 == 0) {
        local_res10[0] = *(undefined4 *)(lVar4 + 0x10);
        uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
        uVar7 = DAT_182242170;
      }
      else {
        uVar7 = *(undefined8 *)(lVar5 + 0x18);
        uVar8 = thunk_FUN_1802038d0(DAT_18225c280);
        FUN_1802e1730(uVar8,lVar4,DAT_182254128,DAT_182215e98);
        cVar2 = FUN_180a5b440(uVar7,uVar8,DAT_18222d778);
        if (cVar2 == '\0') {
          if (lVar6 == 0) goto LAB_1802a473d;
          uVar7 = FUN_180a60d80(lVar6,DAT_182221b98);
          uVar8 = thunk_FUN_1802038d0(DAT_1822565d0);
          FUN_1802e1730(uVar8,lVar4,DAT_1822540e8,DAT_182213ce8);
          uVar7 = FUN_1804373f0(uVar7,uVar8,DAT_18221e628);
          if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_18224a028);
          }
          lVar9 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 8);
          if (lVar9 == 0) {
            if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
              il2cpp_runtime_class_init(DAT_18224a028);
            }
            uVar8 = **(undefined8 **)(DAT_18224a028 + 0xb8);
            lVar9 = thunk_FUN_1802038d0(DAT_18225ebd8);
            FUN_1802e1730(lVar9,uVar8,DAT_182262490,DAT_182213cf8);
            plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 8);
            *plVar10 = lVar9;
            thunk_FUN_180234b30(plVar10,lVar9);
          }
          uVar7 = FUN_1804331f0(uVar7,lVar9,DAT_18221bdb0);
          uVar7 = FUN_1808092c0(uVar7,DAT_18221c038);
          *(undefined8 *)(lVar4 + 0x18) = uVar7;
          thunk_FUN_180234b30(lVar4 + 0x18,uVar7);
          if (*(longlong *)(lVar4 + 0x18) == 0) {
            local_res10[0] = *(undefined4 *)(lVar4 + 0x14);
            uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
            uVar7 = DAT_182242108;
          }
          else {
            uVar7 = FUN_180a60d80(lVar6,DAT_182221818);
            if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
              il2cpp_runtime_class_init(DAT_18224a028);
            }
            lVar6 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x10);
            if (lVar6 == 0) {
              if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
                il2cpp_runtime_class_init(DAT_18224a028);
              }
              uVar8 = **(undefined8 **)(DAT_18224a028 + 0xb8);
              lVar6 = thunk_FUN_1802038d0(DAT_182252f78);
              FUN_1802e1730(lVar6,uVar8,DAT_182255188,DAT_182213778);
              plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x10);
              *plVar10 = lVar6;
              thunk_FUN_180234b30(plVar10,lVar6);
            }
            uVar7 = FUN_1804373f0(uVar7,lVar6,DAT_18221e3a0);
            uVar8 = thunk_FUN_1802038d0(DAT_182252f78);
            FUN_1802e1730(uVar8,lVar4,DAT_1822540b8,DAT_182213778);
            uVar7 = FUN_1804373f0(uVar7,uVar8,DAT_18221e3a0);
            if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
              il2cpp_runtime_class_init(DAT_18224a028);
            }
            lVar6 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x18);
            if (lVar6 == 0) {
              if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
                il2cpp_runtime_class_init(DAT_18224a028);
              }
              uVar8 = **(undefined8 **)(DAT_18224a028 + 0xb8);
              lVar6 = thunk_FUN_1802038d0(DAT_182258140);
              FUN_1802e1730(lVar6,uVar8,DAT_182261728,DAT_182213780);
              plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x18);
              *plVar10 = lVar6;
              thunk_FUN_180234b30(plVar10,lVar6);
            }
            uVar7 = FUN_1804331f0(uVar7,lVar6,DAT_18221bab0);
            lVar6 = FUN_1808092c0(uVar7,DAT_18221bed8);
            if (lVar6 != 0) {
              uVar7 = *(undefined8 *)(lVar4 + 0x18);
              lVar9 = thunk_FUN_1802038d0(DAT_1822521b0);
              FUN_1803b7fa0(lVar9,uVar7,lVar6,0,0);
              if (*(longlong *)(lVar5 + 0x18) != 0) {
                FUN_1814b6a40(*(longlong *)(lVar5 + 0x18),lVar9,DAT_1822287a8);
                lVar6 = *(longlong *)(lVar5 + 0x40);
                if (((lVar9 != 0) && (*(longlong *)(lVar9 + 0x18) != 0)) &&
                   (uVar3 = FUN_180c792a0(*(longlong *)(lVar9 + 0x18),0), lVar6 != 0)) {
                  cVar2 = FUN_18149e2f0(lVar6,uVar3,DAT_18222f948);
                  if (cVar2 == '\0') {
                    lVar6 = *(longlong *)(lVar5 + 0x40);
                    if ((*(longlong *)(lVar9 + 0x18) == 0) ||
                       (uVar3 = FUN_180c792a0(*(longlong *)(lVar9 + 0x18),0), lVar6 == 0))
                    goto LAB_1802a473d;
                    FUN_18149e120(lVar6,uVar3,DAT_18221fcb8);
                  }
                  FUN_18035e240(lVar5,0);
                  if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  lVar5 = FUN_180661ed0(0);
                  if (lVar5 != 0) {
                    lVar5 = *(longlong *)(lVar5 + 0xa0);
                    if ((*(longlong *)(lVar4 + 0x18) != 0) &&
                       (uVar3 = FUN_180c792a0(*(longlong *)(lVar4 + 0x18),0), lVar5 != 0)) {
                      cVar2 = FUN_1813de910(lVar5,uVar3,DAT_182234880);
                      if (cVar2 != '\0') {
                        return lVar9;
                      }
                      if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) &&
                         (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
                        il2cpp_runtime_class_init();
                      }
                      lVar5 = FUN_180661ed0(0);
                      if (lVar5 != 0) {
                        lVar5 = *(longlong *)(lVar5 + 0xa0);
                        if ((*(longlong *)(lVar4 + 0x18) != 0) &&
                           (uVar3 = FUN_180c792a0(*(longlong *)(lVar4 + 0x18),0), lVar5 != 0)) {
                          FUN_1813de600(lVar5,uVar3,DAT_1822348d0);
                          return lVar9;
                        }
                      }
                    }
                  }
                }
              }
              goto LAB_1802a473d;
            }
            local_res10[0] = *(undefined4 *)(lVar4 + 0x14);
            uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
            uVar7 = DAT_1822420e0;
          }
        }
        else {
          local_res10[0] = *(undefined4 *)(lVar4 + 0x10);
          uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
          uVar7 = DAT_182242158;
        }
      }
      uVar7 = FUN_180fee500(uVar7,uVar8,0);
      if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      FUN_18108a160(uVar7,0);
      return 0;
    }
  }
LAB_1802a473d:
  FUN_180237800();
  pcVar1 = (code *)swi(3);
  lVar4 = (*pcVar1)();
  return lVar4;
}



/********************************************************************/
/* OwnedCharacterClient$$ForgetAbility
 * RVA: 0x2AB780
 * Address: 0x1802AB780
 *******************************************************************/


undefined8 FUN_1802ab780(undefined8 param_1,undefined4 param_2,undefined4 param_3,char param_4)

{
  code *pcVar1;
  undefined4 uVar2;
  longlong lVar3;
  longlong lVar4;
  undefined8 uVar5;
  undefined8 uVar6;
  longlong lVar7;
  longlong lVar8;
  longlong *plVar9;
  undefined4 local_res10 [2];
  undefined4 local_38 [4];
  
  if (DAT_181f4df15 == '\0') {
    thunk_FUN_1801fec80(DAT_181757b98);
    DAT_181f4df15 = '\x01';
  }
  lVar3 = thunk_FUN_1802038d0(DAT_182249ea8);
  FUN_180268140(lVar3,0);
  if (lVar3 == 0) {
LAB_1802abf37:
    FUN_180237800();
    pcVar1 = (code *)swi(3);
    uVar5 = (*pcVar1)();
    return uVar5;
  }
  *(undefined4 *)(lVar3 + 0x10) = param_2;
  *(undefined4 *)(lVar3 + 0x14) = param_3;
  if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_180661ed0(0);
  if (lVar4 == 0) goto LAB_1802abf37;
  uVar5 = FUN_1800dc890(0,DAT_182258c70,lVar4);
  uVar6 = thunk_FUN_1802038d0(DAT_18225e7f8);
  FUN_1802e1730(uVar6,lVar3,DAT_182254c68,DAT_182215d50);
  uVar5 = FUN_180438200(uVar5,uVar6,DAT_18221f3b0);
  lVar4 = FUN_1808092c0(uVar5,DAT_18221bad0);
  if (lVar4 == 0) {
    local_res10[0] = *(undefined4 *)(lVar3 + 0x10);
    uVar5 = il2cpp_value_box(DAT_18221c5c0,local_res10);
    uVar5 = FUN_180fee500(DAT_182241fc0,uVar5,0);
LAB_1802abf05:
    if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    FUN_18108a160(uVar5,0);
    uVar5 = 0;
  }
  else {
    if (param_4 == '\0') {
      FUN_1802ada80(param_1,*(undefined4 *)(lVar3 + 0x10),*(undefined4 *)(lVar3 + 0x14),0);
    }
    else {
      lVar7 = thunk_FUN_1802038d0(DAT_182249e98);
      FUN_180268140(lVar7,0);
      uVar5 = *(undefined8 *)(lVar4 + 0x18);
      if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar8 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x40);
      if (lVar8 == 0) {
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar6 = **(undefined8 **)(DAT_18224a028 + 0xb8);
        lVar8 = thunk_FUN_1802038d0(DAT_18225c280);
        FUN_1802e1730(lVar8,uVar6,DAT_182255070,DAT_182215e98);
        plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x40);
        *plVar9 = lVar8;
        thunk_FUN_180234b30(plVar9,lVar8);
      }
      uVar5 = FUN_180438200(uVar5,lVar8,DAT_18221f3f0);
      uVar6 = thunk_FUN_1802038d0(DAT_18225c280);
      FUN_1802e1730(uVar6,lVar3,DAT_182254c20,DAT_182215e98);
      uVar5 = FUN_180438200(uVar5,uVar6,DAT_18221f3f0);
      if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18224a028);
      }
      lVar8 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x48);
      if (lVar8 == 0) {
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18224a028);
        }
        uVar6 = **(undefined8 **)(DAT_18224a028 + 0xb8);
        lVar8 = thunk_FUN_1802038d0(DAT_182249e50);
        FUN_1802e1730(lVar8,uVar6,DAT_18220c898,DAT_182215e78);
        plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x48);
        *plVar9 = lVar8;
        thunk_FUN_180234b30(plVar9,lVar8);
      }
      uVar5 = FUN_180433e50(uVar5,lVar8,DAT_18221c9f0);
      uVar2 = FUN_1808081c0(uVar5,DAT_182219ed0);
      if (lVar7 == 0) goto LAB_1802abf37;
      *(undefined4 *)(lVar7 + 0x10) = uVar2;
      uVar5 = *(undefined8 *)(lVar4 + 0x20);
      uVar6 = thunk_FUN_1802038d0(DAT_182249fb0);
      FUN_1802e1730(uVar6,lVar7,DAT_182254bd8,DAT_182215e00);
      uVar5 = FUN_180438200(uVar5,uVar6,DAT_18221f3e8);
      if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18224a028);
      }
      lVar4 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x50);
      if (lVar4 == 0) {
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18224a028);
        }
        uVar6 = **(undefined8 **)(DAT_18224a028 + 0xb8);
        lVar4 = thunk_FUN_1802038d0(DAT_182249e20);
        FUN_1802e1730(lVar4,uVar6,DAT_182221c68,DAT_182215dd8);
        plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x50);
        *plVar9 = lVar4;
        thunk_FUN_180234b30(plVar9,lVar4);
      }
      uVar5 = FUN_180434430(uVar5,lVar4,DAT_18221c9b0);
      lVar4 = FUN_1808092c0(uVar5,DAT_18221a6c8);
      if (lVar4 == 0) {
        plVar9 = (longlong *)FUN_180237470(DAT_18221b6d0,4);
        if (plVar9 == (longlong *)0x0) {
          FUN_180237800();
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        if ((DAT_182241fb0 != 0) &&
           (lVar4 = thunk_FUN_1802008c0(DAT_182241fb0,*(undefined8 *)(*plVar9 + 0x40)), lVar4 == 0))
        {
          uVar5 = thunk_FUN_1801f1c80();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        lVar4 = DAT_182241fb0;
        if (*(int *)(plVar9 + 3) == 0) {
          uVar5 = thunk_FUN_1801f50f0();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        plVar9[4] = DAT_182241fb0;
        thunk_FUN_180234b30(plVar9 + 4,lVar4);
        local_res10[0] = *(undefined4 *)(lVar3 + 0x10);
        lVar3 = il2cpp_value_box(DAT_18221c5c0,local_res10);
        if ((lVar3 != 0) &&
           (lVar4 = thunk_FUN_1802008c0(lVar3,*(undefined8 *)(*plVar9 + 0x40)), lVar4 == 0)) {
          uVar5 = thunk_FUN_1801f1c80();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        if (*(uint *)(plVar9 + 3) < 2) {
          uVar5 = thunk_FUN_1801f50f0();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        plVar9[5] = lVar3;
        thunk_FUN_180234b30(plVar9 + 5,lVar3);
        if ((DAT_182241f78 != 0) &&
           (lVar3 = thunk_FUN_1802008c0(DAT_182241f78,*(undefined8 *)(*plVar9 + 0x40)), lVar3 == 0))
        {
          uVar5 = thunk_FUN_1801f1c80();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        lVar3 = DAT_182241f78;
        if (*(uint *)(plVar9 + 3) < 3) {
          uVar5 = thunk_FUN_1801f50f0();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        plVar9[6] = DAT_182241f78;
        thunk_FUN_180234b30(plVar9 + 6,lVar3);
        local_38[0] = *(undefined4 *)(lVar7 + 0x10);
        lVar3 = il2cpp_value_box(DAT_18221c5c0,local_38);
        if ((lVar3 != 0) &&
           (lVar4 = thunk_FUN_1802008c0(lVar3,*(undefined8 *)(*plVar9 + 0x40)), lVar4 == 0)) {
          uVar5 = thunk_FUN_1801f1c80();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        if (*(uint *)(plVar9 + 3) < 4) {
          uVar5 = thunk_FUN_1801f50f0();
          FUN_1802377d0(uVar5,0);
          pcVar1 = (code *)swi(3);
          uVar5 = (*pcVar1)();
          return uVar5;
        }
        plVar9[7] = lVar3;
        thunk_FUN_180234b30(plVar9 + 7,lVar3);
        uVar5 = FUN_180fee2c0(plVar9,0);
        goto LAB_1802abf05;
      }
      if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar8 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x58);
      if (lVar8 == 0) {
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar5 = **(undefined8 **)(DAT_18224a028 + 0xb8);
        lVar8 = thunk_FUN_1802038d0(DAT_182252220);
        FUN_1802e1730(lVar8,uVar5,DAT_182255050,DAT_182212d40);
        plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x58);
        *plVar9 = lVar8;
        thunk_FUN_180234b30(plVar9,lVar8);
      }
      uVar5 = FUN_1804373f0(lVar4,lVar8,DAT_18221df18);
      uVar6 = thunk_FUN_1802038d0(DAT_182252220);
      FUN_1802e1730(uVar6,lVar3,DAT_182254c00,DAT_182212d40);
      uVar5 = FUN_1804373f0(uVar5,uVar6,DAT_18221df18);
      if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18224a028);
      }
      lVar4 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x60);
      if (lVar4 == 0) {
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18224a028);
        }
        uVar6 = **(undefined8 **)(DAT_18224a028 + 0xb8);
        lVar4 = thunk_FUN_1802038d0(DAT_182249f68);
        FUN_1802e1730(lVar4,uVar6,DAT_18220c860,DAT_182212d10);
        plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x60);
        *plVar9 = lVar4;
        thunk_FUN_180234b30(plVar9,lVar4);
      }
      uVar5 = FUN_180432f00(uVar5,lVar4,DAT_18221b650);
      uVar2 = FUN_1808081c0(uVar5,DAT_182219ed0);
      FUN_1802adee0(param_1,*(undefined4 *)(lVar3 + 0x10),*(undefined4 *)(lVar7 + 0x10),uVar2,1,0);
    }
    uVar5 = 1;
  }
  return uVar5;
}



/********************************************************************/
/* OwnedCharacterClient$$RemoveAbility
 * RVA: 0x2ADA80
 * Address: 0x1802ADA80
 *******************************************************************/


void FUN_1802ada80(undefined8 param_1,undefined4 param_2,undefined4 param_3)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  longlong lVar4;
  undefined8 uVar5;
  undefined8 uVar6;
  longlong lVar7;
  longlong lVar8;
  longlong lVar9;
  undefined4 uVar10;
  undefined4 local_88 [4];
  undefined4 *local_78;
  longlong local_70;
  longlong local_68;
  undefined4 local_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined8 local_48;
  undefined4 local_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined8 local_30;
  
  if (DAT_181f4df10 == '\0') {
    thunk_FUN_1801fec80(DAT_181757c50);
    DAT_181f4df10 = '\x01';
  }
  local_78 = local_88;
  lVar3 = thunk_FUN_1802038d0(DAT_18224a020);
  FUN_180268140(lVar3,0);
  if (lVar3 != 0) {
    *(undefined4 *)(lVar3 + 0x10) = param_2;
    *(undefined4 *)(lVar3 + 0x14) = param_3;
    if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar4 = FUN_180661ed0(0);
    if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    FUN_180ea8da0(DAT_182245a60);
    if (lVar4 != 0) {
      uVar5 = FUN_1800dc890(0,DAT_182258c70,lVar4);
      uVar6 = thunk_FUN_1802038d0(DAT_18225e7f8);
      FUN_1802e1730(uVar6,lVar3,DAT_182253ee8,DAT_182215d50);
      uVar5 = FUN_180438200(uVar5,uVar6,DAT_18221f3b0);
      lVar4 = FUN_1808092c0(uVar5,DAT_18221bad0);
      local_70 = lVar4;
      if (lVar4 == 0) {
        uVar5 = DAT_1822420c8;
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
          uVar5 = DAT_1822420c8;
        }
      }
      else {
        uVar5 = *(undefined8 *)(lVar4 + 0x18);
        uVar6 = thunk_FUN_1802038d0(DAT_18225c280);
        FUN_1802e1730(uVar6,lVar3,DAT_182253eb0,DAT_182215e98);
        uVar5 = FUN_180438200(uVar5,uVar6,DAT_18221f3f0);
        lVar7 = FUN_1808092c0(uVar5,DAT_18221bb78);
        local_68 = lVar7;
        if (lVar7 != 0) {
          if (*(longlong *)(lVar4 + 0x10) != 0) {
            FUN_1812b2ca0(&local_40,*(longlong *)(lVar4 + 0x10),DAT_182218018);
            local_58 = local_40;
            uStack_54 = uStack_3c;
            uStack_50 = uStack_38;
            uStack_4c = uStack_34;
            local_48 = local_30;
            while (cVar2 = FUN_180aebf80(&local_58,DAT_182233e90), uVar5 = local_48, cVar2 != '\0')
            {
              if (*(longlong *)(lVar4 + 0x50) == 0) goto LAB_1802adec9;
              uVar6 = FUN_18110c270(*(longlong *)(lVar4 + 0x50),DAT_1822227f0);
              cVar2 = FUN_180a5c400(uVar6,uVar5,DAT_18222c2f8);
              if (cVar2 != '\0') {
                if (*(longlong *)(lVar4 + 0x50) == 0) goto LAB_1802adec4;
                uVar6 = FUN_1813b8190(*(longlong *)(lVar4 + 0x50),uVar5,DAT_182208f70);
                lVar8 = *(longlong *)(lVar3 + 0x18);
                if (lVar8 == 0) {
                  lVar8 = thunk_FUN_1802038d0(DAT_18225c280);
                  FUN_1802e1730(lVar8,lVar3,DAT_182253e88,DAT_182215e98);
                  *(longlong *)(lVar3 + 0x18) = lVar8;
                  thunk_FUN_180234b30(lVar3 + 0x18,lVar8);
                }
                uVar6 = FUN_180438200(uVar6,lVar8,DAT_18221f3f0);
                lVar8 = FUN_1808092c0(uVar6,DAT_18221bb78);
                if (lVar8 != 0) {
                  if (*(longlong *)(lVar4 + 0x50) == 0) goto LAB_1802adebf;
                  lVar9 = FUN_1813b8190(*(longlong *)(lVar4 + 0x50),uVar5,DAT_182208f70);
                  if (lVar9 == 0) goto LAB_1802adeb9;
                  FUN_1813d3420(lVar9,lVar8,DAT_182230140);
                }
              }
            }
            *local_78 = 0x10b;
            FUN_1802698f0(&local_58,DAT_18222f148);
            if (*(longlong *)(lVar4 + 0x18) != 0) {
              FUN_1813d3420(*(longlong *)(lVar4 + 0x18),lVar7,DAT_182230140);
              lVar3 = *(longlong *)(lVar4 + 0x40);
              if ((*(longlong *)(lVar7 + 0x18) != 0) &&
                 (uVar10 = FUN_180c792a0(*(longlong *)(lVar7 + 0x18),0), lVar3 != 0)) {
                cVar2 = FUN_18149e2f0(lVar3,uVar10,DAT_18222f948);
                if (cVar2 == '\0') {
                  return;
                }
                lVar3 = *(longlong *)(lVar4 + 0x40);
                if ((*(longlong *)(lVar7 + 0x18) != 0) &&
                   (uVar10 = FUN_180c792a0(*(longlong *)(lVar7 + 0x18),0), lVar3 != 0)) {
                  FUN_1813d3420(lVar3,uVar10,DAT_18222f910);
                  return;
                }
              }
            }
          }
          goto LAB_1802adeb3;
        }
        uVar5 = DAT_182242098;
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
          uVar5 = DAT_182242098;
        }
      }
      FUN_18108a160(uVar5,0);
      return;
    }
  }
LAB_1802adeb3:
  FUN_180237800();
LAB_1802adeb9:
  FUN_180237800();
LAB_1802adebf:
  FUN_180237800();
LAB_1802adec4:
  FUN_180237800();
LAB_1802adec9:
  uVar10 = FUN_180237800();
  FUN_1802377d0(uVar10,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* OwnedCharacterClient$$SetAbility
 * RVA: 0x2AF850
 * Address: 0x1802AF850
 *******************************************************************/


undefined8
FUN_1802af850(undefined8 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  undefined4 uVar1;
  code *pcVar2;
  undefined4 uVar3;
  longlong lVar4;
  longlong lVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  longlong *plVar9;
  undefined4 local_res10 [2];
  
  if (DAT_181f4df12 == '\0') {
    thunk_FUN_1801fec80(DAT_181757d28);
    DAT_181f4df12 = '\x01';
  }
  lVar4 = thunk_FUN_1802038d0(DAT_182249f48);
  FUN_180268140(lVar4,0);
  if (lVar4 != 0) {
    *(undefined4 *)(lVar4 + 0x10) = param_2;
    *(undefined4 *)(lVar4 + 0x14) = param_3;
    if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar5 = FUN_180661ed0(0);
    if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar6 = FUN_180ea8da0(DAT_182245a60);
    if (lVar5 != 0) {
      uVar7 = FUN_1800dc890(0,DAT_182258c70,lVar5);
      uVar8 = thunk_FUN_1802038d0(DAT_18225e7f8);
      FUN_1802e1730(uVar8,lVar4,DAT_182253d10,DAT_182215d50);
      uVar7 = FUN_180438200(uVar7,uVar8,DAT_18221f3b0);
      lVar5 = FUN_1808092c0(uVar7,DAT_18221bad0);
      if (lVar5 == 0) {
        uVar7 = DAT_182242050;
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
          uVar7 = DAT_182242050;
        }
      }
      else {
        if (lVar6 == 0) goto LAB_1802afc76;
        uVar7 = FUN_180a60d80(lVar6,DAT_182221b98);
        uVar8 = thunk_FUN_1802038d0(DAT_1822565d0);
        FUN_1802e1730(uVar8,lVar4,DAT_182253cd8,DAT_182213ce8);
        uVar7 = FUN_1804373f0(uVar7,uVar8,DAT_18221e628);
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18224a028);
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x38);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_18224a028);
          }
          uVar8 = **(undefined8 **)(DAT_18224a028 + 0xb8);
          lVar6 = thunk_FUN_1802038d0(DAT_18225ebd8);
          FUN_1802e1730(lVar6,uVar8,DAT_182262448,DAT_182213cf8);
          plVar9 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x38);
          *plVar9 = lVar6;
          thunk_FUN_180234b30(plVar9,lVar6);
        }
        uVar7 = FUN_1804331f0(uVar7,lVar6,DAT_18221bdb0);
        uVar7 = FUN_1808092c0(uVar7,DAT_18221c038);
        *(undefined8 *)(lVar4 + 0x18) = uVar7;
        thunk_FUN_180234b30(lVar4 + 0x18,uVar7);
        if (*(longlong *)(lVar4 + 0x18) == 0) {
          local_res10[0] = *(undefined4 *)(lVar4 + 0x14);
          uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
          uVar7 = DAT_182242108;
        }
        else {
          uVar7 = *(undefined8 *)(lVar5 + 0x20);
          uVar8 = thunk_FUN_1802038d0(DAT_182249fb0);
          FUN_1802e1730(uVar8,lVar4,DAT_182253ca0,DAT_182215e00);
          uVar7 = FUN_180438200(uVar7,uVar8,DAT_18221f3e8);
          lVar5 = FUN_1808092c0(uVar7,DAT_18221bb00);
          if (lVar5 != 0) {
            if (*(longlong *)(lVar5 + 0x10) != 0) {
              lVar6 = FUN_1813fb000(*(longlong *)(lVar5 + 0x10),param_4,DAT_1822084a8);
              if (lVar6 != 0) {
                uVar1 = *(undefined4 *)(lVar4 + 0x10);
                if (*(longlong *)(lVar6 + 0x10) == 0) goto LAB_1802afc76;
                uVar3 = FUN_180c792a0(*(longlong *)(lVar6 + 0x10),0);
                FUN_1802ada80(param_1,uVar1,uVar3,0);
              }
              uVar1 = *(undefined4 *)(lVar4 + 0x10);
              if (*(longlong *)(lVar4 + 0x18) != 0) {
                uVar3 = FUN_180c792a0(*(longlong *)(lVar4 + 0x18),0);
                uVar7 = FUN_1802a4050(param_1,uVar1,uVar3,0);
                if (*(longlong *)(lVar5 + 0x10) != 0) {
                  FUN_1812b14a0(*(longlong *)(lVar5 + 0x10),param_4,uVar7,DAT_18223a198);
                  return 1;
                }
              }
            }
            goto LAB_1802afc76;
          }
          if (*(longlong *)(lVar4 + 0x18) == 0) {
            FUN_180237800();
            pcVar2 = (code *)swi(3);
            uVar7 = (*pcVar2)();
            return uVar7;
          }
          local_res10[0] = FUN_180c79510(*(longlong *)(lVar4 + 0x18),0);
          uVar8 = il2cpp_value_box(DAT_18221c5c0,local_res10);
          uVar7 = DAT_182242020;
        }
        uVar7 = FUN_180fee500(uVar7,uVar8,0);
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
      }
      FUN_18108a160(uVar7,0);
      return 0;
    }
  }
LAB_1802afc76:
  FUN_180237800();
  pcVar2 = (code *)swi(3);
  uVar7 = (*pcVar2)();
  return uVar7;
}



/********************************************************************/
/* OwnedCharacterClient$$SetSlotAbility
 * RVA: 0x2B1350
 * Address: 0x1802B1350
 *******************************************************************/


undefined8 FUN_1802b1350(undefined8 param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  code *pcVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  longlong lVar5;
  longlong lVar6;
  longlong lVar7;
  undefined8 uVar8;
  undefined8 uVar9;
  longlong *plVar10;
  undefined4 local_res10 [2];
  
  if (DAT_181f4df11 == '\0') {
    thunk_FUN_1801fec80(DAT_181757e04);
    DAT_181f4df11 = '\x01';
  }
  lVar5 = thunk_FUN_1802038d0(DAT_182249fc8);
  FUN_180268140(lVar5,0);
  if (lVar5 != 0) {
    *(undefined4 *)(lVar5 + 0x10) = param_2;
    *(undefined4 *)(lVar5 + 0x14) = param_3;
    if (((*(byte *)(DAT_18225d698 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d698 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar6 = FUN_180661ed0(0);
    if (((*(byte *)(DAT_18225ec40 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225ec40 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar7 = FUN_180ea8da0(DAT_182245a60);
    if (lVar6 != 0) {
      uVar8 = FUN_1800dc890(0,DAT_182258c70,lVar6);
      uVar9 = thunk_FUN_1802038d0(DAT_18225e7f8);
      FUN_1802e1730(uVar9,lVar5,DAT_182253d78,DAT_182215d50);
      uVar8 = FUN_180438200(uVar8,uVar9,DAT_18221f3b0);
      lVar6 = FUN_1808092c0(uVar8,DAT_18221bad0);
      if (lVar6 == 0) {
        uVar8 = DAT_182242050;
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
          uVar8 = DAT_182242050;
        }
      }
      else {
        if (lVar7 == 0) goto LAB_1802b18aa;
        uVar8 = FUN_180a60d80(lVar7,DAT_182221b98);
        uVar9 = thunk_FUN_1802038d0(DAT_1822565d0);
        FUN_1802e1730(uVar9,lVar5,DAT_182253d50,DAT_182213ce8);
        uVar8 = FUN_1804373f0(uVar8,uVar9,DAT_18221e628);
        if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18224a028);
        }
        lVar7 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x20);
        if (lVar7 == 0) {
          if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) && (*(int *)(DAT_18224a028 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_18224a028);
          }
          uVar9 = **(undefined8 **)(DAT_18224a028 + 0xb8);
          lVar7 = thunk_FUN_1802038d0(DAT_18225ebd8);
          FUN_1802e1730(lVar7,uVar9,DAT_182262418,DAT_182213cf8);
          plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x20);
          *plVar10 = lVar7;
          thunk_FUN_180234b30(plVar10,lVar7);
        }
        uVar8 = FUN_1804331f0(uVar8,lVar7,DAT_18221bdb0);
        uVar8 = FUN_1808092c0(uVar8,DAT_18221c038);
        *(undefined8 *)(lVar5 + 0x18) = uVar8;
        thunk_FUN_180234b30(lVar5 + 0x18,uVar8);
        if (*(longlong *)(lVar5 + 0x18) == 0) {
          local_res10[0] = *(undefined4 *)(lVar5 + 0x14);
          uVar9 = il2cpp_value_box(DAT_18221c5c0,local_res10);
          uVar8 = DAT_182242108;
        }
        else {
          uVar8 = *(undefined8 *)(lVar6 + 0x20);
          uVar9 = thunk_FUN_1802038d0(DAT_182249fb0);
          FUN_1802e1730(uVar9,lVar5,DAT_182253d18,DAT_182215e00);
          uVar8 = FUN_180438200(uVar8,uVar9,DAT_18221f3e8);
          lVar6 = FUN_1808092c0(uVar8,DAT_18221bb00);
          if (lVar6 != 0) {
            uVar8 = *(undefined8 *)(lVar6 + 0x10);
            if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar7 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x28);
            if (lVar7 == 0) {
              if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              uVar9 = **(undefined8 **)(DAT_18224a028 + 0xb8);
              lVar7 = thunk_FUN_1802038d0(DAT_182252220);
              FUN_1802e1730(lVar7,uVar9,DAT_182254f48,DAT_182212d40);
              plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x28);
              *plVar10 = lVar7;
              thunk_FUN_180234b30(plVar10,lVar7);
            }
            uVar8 = FUN_1804373f0(uVar8,lVar7,DAT_18221df18);
            if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
              il2cpp_runtime_class_init(DAT_18224a028);
            }
            lVar7 = *(longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x30);
            if (lVar7 == 0) {
              if (((*(byte *)(DAT_18224a028 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18224a028 + 0xe0) == 0)) {
                il2cpp_runtime_class_init(DAT_18224a028);
              }
              uVar9 = **(undefined8 **)(DAT_18224a028 + 0xb8);
              lVar7 = thunk_FUN_1802038d0(DAT_182249f68);
              FUN_1802e1730(lVar7,uVar9,DAT_18220c838,DAT_182212d10);
              plVar10 = (longlong *)(*(longlong *)(DAT_18224a028 + 0xb8) + 0x30);
              *plVar10 = lVar7;
              thunk_FUN_180234b30(plVar10,lVar7);
            }
            uVar8 = FUN_180432f00(uVar8,lVar7,DAT_18221b650);
            uVar3 = FUN_1808081c0(uVar8,DAT_182219ed0);
            uVar1 = *(undefined4 *)(lVar5 + 0x10);
            if (*(longlong *)(lVar5 + 0x18) != 0) {
              uVar4 = FUN_180c792a0(*(longlong *)(lVar5 + 0x18),0);
              uVar8 = FUN_1802a4050(param_1,uVar1,uVar4,0);
              if (*(longlong *)(lVar6 + 0x10) != 0) {
                FUN_1812b14a0(*(longlong *)(lVar6 + 0x10),uVar3,uVar8,DAT_18223a198);
                return 1;
              }
            }
            goto LAB_1802b18aa;
          }
          if (*(longlong *)(lVar5 + 0x18) == 0) {
            FUN_180237800();
            pcVar2 = (code *)swi(3);
            uVar8 = (*pcVar2)();
            return uVar8;
          }
          local_res10[0] = FUN_180c79510(*(longlong *)(lVar5 + 0x18),0);
          uVar9 = il2cpp_value_box(DAT_18221c5c0,local_res10);
          uVar8 = DAT_182242020;
        }
        uVar8 = FUN_180fee500(uVar8,uVar9,0);
        if (((*(byte *)(DAT_18220f808 + 0x12f) & 2) != 0) && (*(int *)(DAT_18220f808 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
      }
      FUN_18108a160(uVar8,0);
      return 0;
    }
  }
LAB_1802b18aa:
  FUN_180237800();
  pcVar2 = (code *)swi(3);
  uVar8 = (*pcVar2)();
  return uVar8;
}

